### ISSUE TITLE
是否支持weex或者nvue啊

### ISSUE THREAD

**Issue by cntlis** [HuLuoQian/uni-inputs#1]
是否支持weex或者nvue啊

**Comment by HuLuoQian** [comment]
额 不是在nvue 环境下写的这个插件， 我写的时候好早了，最开始还是 非自定义组件模式写的，现在是 自定义组件模式下可以使用， vue页面




------------------ 原始邮件 ------------------
发件人: "EchoYu"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 下午4:46
收件人: "HuLuoQian/uni-inputs"<uni-inputs@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [HuLuoQian/uni-inputs] 是否支持weex或者nvue啊 (#1)




是否支持weex或者nvue啊
